# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [96]:
url = 'https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv'
chipo = pd.read_csv(url,sep='\t')

### Step 4. How many products cost more than $10.00?

In [97]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')

In [98]:
chipo.head(5)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [99]:
# need more information about the data 
# what does item_price mean ????
chipo.item_price = chipo.item_price.map(lambda x: np.float(x[1:]))
chipo[chipo['item_price']>10].item_name.nunique()

31

### Step 5. What is the price of each item? 
###### print a data frame with only two columns item_name and item_price

In [78]:
price_per_item = chipo[['item_name', 'item_price']]
price_per_item = round(price_per_item.groupby(by='item_name').mean(),2)
price_per_item.sort_values(by='item_price',ascending=False)

                                       item_price
item_name
Bowl                                        14.80
Steak Salad Bowl                            11.85
Chicken Salad Bowl                          11.17
Carnitas Crispy Tacos                       11.14
Carnitas Salad Bowl                         11.06
Barbacoa Crispy Tacos                       10.93
Carnitas Bowl                               10.83
Steak Bowl                                  10.71
Barbacoa Salad Bowl                         10.64
Veggie Soft Tacos                           10.57
Steak Burrito                               10.47
Steak Crispy Tacos                          10.21
Veggie Bowl                                 10.21
Barbacoa Bowl                               10.19
Veggie Salad Bowl                           10.14
Carnitas Burrito                            10.13
Chicken Bowl                                10.11
Chicken Burrito                             10.08
Chicken Crispy Tacos                        10.05
Barbacoa Soft Tacos                         10.02
Veggie Burrito                               9.84
Barbacoa Burrito                             9.83
Steak Soft Tacos                             9.75
Chicken Soft Tacos                           9.64
Carnitas Soft Tacos                          9.40
Chicken Salad                                9.01
Carnitas Salad                               8.99
Steak Salad                                  8.91
Veggie Crispy Tacos                          8.49
Veggie Salad                                 8.49
Crispy Tacos                                 7.40
Burrito                                      7.40
Salad                                        7.40
6 Pack Soft Drink                            6.61
Chips and Guacamole                          4.60
Nantucket Nectar                             3.64
Izze                                         3.39
Chips and Fresh Tomato Salsa                 3.29
Chips and Tomatillo Green Chili Salsa        3.09
Chips and Roasted Chili Corn Salsa           3.08
Chips and Tomatillo Red Chili Salsa          3.07
Chips and Mild Fresh Tomato Salsa            3.00
Chips and Tomatillo-Red Chili Salsa          2.99
Chips and Tomatillo-Green Chili Salsa        2.54
Chips and Roasted Chili-Corn Salsa           2.39
Chips                                        2.34
Bottled Water                                1.87
Side of Chips                                1.84
Canned Soft Drink                            1.46
Canned Soda                                  1.32

### Step 6. Sort by the name of the item

In [80]:
chipo.sort_values(by='item_name')

,order_id,quantity,item_name,choice_description,item_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
1849,749,1,6 Pack Soft Drink,[Coke],6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
2713,1076,1,6 Pack Soft Drink,[Coke],6.49
3422,1373,1,6 Pack Soft Drink,[Coke],6.49
553,230,1,6 Pack Soft Drink,[Diet Coke],6.49
1916,774,1,6 Pack Soft Drink,[Diet Coke],6.49
1922,776,1,6 Pack Soft Drink,[Coke],6.49
1937,784,1,6 Pack Soft Drink,[Diet Coke],6.49
3836,1537,1,6 Pack Soft Drink,[Coke],6.49
298,129,1,6 Pack Soft Drink,[Sprite],6.49
1976,798,1,6 Pack Soft Drink,[Diet Coke],6.49
1167,481,1,6 Pack Soft Drink,[Coke],6.49
3875,1554,1,6 Pack Soft Drink,[Diet Coke],6.49
1124,465,1,6 Pack Soft Drink,[Coke],6.49
3886,1558,1,6 Pack Soft Drink,[Diet Coke],6.49
2108,849,1,6 Pack Soft Drink,[Coke],6.49
3010,1196,1,6 Pack Soft Drink,[Diet Coke],6.49
4535,1803,1,6 Pack Soft Drink,[Lemonade],6.49
4169,1664,1,6 Pack Soft Drink,[Diet Coke],6.49
4174,1666,1,6 Pack Soft Drink,[Coke],6.49
4527,1800,1,6 Pack Soft Drink,[Diet Coke],6.49
4522,1798,1,6 Pack Soft Drink,[Diet Coke],6.49
3806,1525,1,6 Pack Soft Drink,[Sprite],6.49
2389,949,1,6 Pack Soft Drink,[Coke],6.49
3132,1248,1,6 Pack Soft Drink,[Diet Coke],6.49
3141,1253,1,6 Pack Soft Drink,[Lemonade],6.49
639,264,1,6 Pack Soft Drink,[Diet Coke],6.49
1026,422,1,6 Pack Soft Drink,[Sprite],6.49
...,...,...,...,...,...
2996,1192,1,Veggie Salad,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
3163,1263,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
4084,1635,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
1694,686,1,Veggie Salad,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",8.49
2756,1094,1,Veggie Salad,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.49
4201,1677,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",11.25
1884,760,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
455,195,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
3223,1289,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
2223,896,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, Fajita Vegetables]",8.75
2269,913,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
4541,1805,1,Veggie Salad Bowl,"[Tomatillo Green Chili Salsa, [Fajita Vegetabl...",8.75
3293,1321,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
186,83,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
960,394,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
1316,536,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",8.75
2156,869,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4261,1700,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
295,128,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",11.25
4573,1818,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75
2683,1066,1,Veggie Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
496,207,1,Veggie Salad Bowl,"[Fresh Tomato Salsa, [Rice, Lettuce, Guacamole...",11.25
4109,1646,1,Veggie Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
738,304,1,Veggie Soft Tacos,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
3889,1559,2,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",16.98
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [101]:
# what does item_price mean ????
chipo.sort_values(by = "item_price", ascending = False).head(5)

,order_id,quantity,item_name,choice_description,item_price
3598,1443,15,Chips and Fresh Tomato Salsa,NaN,44.25
3480,1398,3,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",35.25
1254,511,4,Chicken Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",35.00
3602,1443,4,Chicken Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",35.00
3601,1443,3,Veggie Burrito,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",33.75

### Step 8. How many times were a Veggie Salad Bowl ordered?

In [103]:
chipo_Veggie = chipo[chipo.item_name == "Veggie Salad Bowl"]
len(chipo_Veggie)

18

### Step 9. How many times people orderd more than one Canned Soda?

In [105]:
chipo_Canned = chipo[chipo.item_name == "Canned Soda"]
chipo_Canned = chipo_Canned[chipo.quantity > 1]
len(chipo_Canned)

//anaconda/envs/py3/lib/python3.6/site-packages/ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.

20